version: '3'
services:
  web:
    image: celery-app  # Use the name of your app's Docker image
    ports:
      - "8000:8000"
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
